# Generated by Django 6.0.4 on 2026-04-18 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggota',
            options={'ordering': ['nama'], 'verbose_name': 'Anggota', 'verbose_name_plural': 'Manajemen Anggota'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Layanan', 'verbose_name_plural': 'Daftar Layanan'},
        ),
        migrations.AddField(
            model_name='anggota',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografi Singkat'),
        ),
        migrations.AddField(
            model_name='anggota',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='foto',
            field=models.ImageField(blank=True, help_text='Upload foto profil tim', null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anggota',
            name='jabatan',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('DEV', 'Developer'), ('IOT', 'IoT Engineer'), ('DSN', 'Designer')], default='DEV', max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='deskripsi',
            field=models.TextField(verbose_name='Deskripsi Layanan'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ikon',
            field=models.CharField(help_text='Gunakan class FontAwesome (misal: fas fa-code)', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='judul',
            field=models.CharField(max_length=100, verbose_name='Nama Layanan'),
        ),
    ]
