# Generated by Django 6.0.4 on 2026-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AlterField(
            model_name='anggota',
            name='jabatan',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('DEV', 'Developer'), ('IOT', 'IoT Engineer'), ('DSN', 'Designer')], default='DEV', max_length=5),
        ),
    ]
